[package]
name = "private-box-native"
version = "0.1.0"
authors = ["Piet Geursen <pietgeursen@gmail.com>"]
license = "MIT"

[lib]
name = "private_box_native"
crate-type = ["cdylib"]
stage = 1

[dependencies.private-box]
path="../../private-box-rs"
stage = 0
