[env]
SODIUM_STATIC="1"
SODIUM_DIR="${CARGO_MAKE_WORKING_DIRECTORY}/target/libsodium"
SODIUM_INSTALL_DIR="${SODIUM_DIR}/install_dir"
SODIUM_LIB_DIR="${SODIUM_INSTALL_DIR}/lib"

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--write-mode=overwrite"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.sodium_clone]
script = [
	"[ -d ${SODIUM_DIR} ] || git clone https://github.com/jedisct1/libsodium ${SODIUM_DIR}"
]

[tasks.sodium_fetch]
command = "git"
args = ["-C", "${SODIUM_DIR}","fetch"]
dependencies = ["sodium_clone"]

[tasks.sodium_checkout]
command = "git"
args = ["-C",  "${SODIUM_DIR}","checkout", "origin/stable"]
dependencies = ["sodium_fetch"]

[tasks.sodium_make_install]
script = [
	"cd ${SODIUM_DIR}",
	"./autogen.sh",
	"./configure --prefix=${SODIUM_INSTALL_DIR} --disable-shared --enable-static --disable-pie",
	"make",
	"make install",
]
dependencies = ["sodium_checkout"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["sodium_make_install"]

[tasks.configure_napi_binding]
command = "cmake" 
args = ["."]

[tasks.build_napi_binding]
command = "make"
dependencies = ["configure_napi_binding"]

[tasks.mv_napi_binding]
command = "mv"
args = ["libbinding.so", "binding.node"]
dependencies = ["build_napi_binding"]

[tasks.my-flow]
dependencies = [
		"build",
    "sodium_make_install",
		"mv_napi_binding"
]
